import type { Metadata } from "next";
import "./globals.css";
import { Vazirmatn } from "next/font/google";
import Link from "next/link";
import { ChartColumnBigIcon } from "lucide-react";

const vazir = Vazirmatn({
  subsets: ["arabic", "latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-vazir",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`${vazir.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <nav className="bg-primary p-4 text-white h-20 flex items-center justify-between">
          <Link
            href={"/"}
            className="font-black text-2xl flex items-center gap-1"
          >
            <ChartColumnBigIcon className="text-lime-500" /> صورتحساب
          </Link>
          <div>دکمهای ثبتنام و ورود</div>
        </nav>
        {children}
      </body>
    </html>
  );
}
